services:
  postgres:
    image: postgres:17-alpine
    container_name: crud_bd
    restart: always
    ports:
      - 5433:5432
    env_file:
      - .env
    volumes:
      - postgres-volume:/var/lib/postgresql/data

  node:
    container_name: crud_backend
    build: ./
    restart: always
    ports:
      - 5000:5000
    depends_on:
      - postgres
    env_file:
      - .env

volumes:
  postgres-volume:
